version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '09:00'
    timezone: Asia/Tokyo